# services.yaml
submit_movie_request:
  description: Searches for a movie and requests the first result.
  fields:
    name:
      description: Search parameter
      example: "beverly hills cop"

submit_tv_request:
  description: Searches for a TV show and requests the first result.
  fields:
    name:
      description: Search parameter
      example: "breaking bad"
    season:
      description: Which season(s) to request (first, latest or all)
      example: "latest"
      selector:
        select:
          options:
            - "first"
            - "latest"
            - "all"

submit_music_request:
  description: Searches for a music album and requests the first result.
  fields:
    name:
      description: Search parameter
      example: "nevermind"

update_media_status:
  description: Updates the status of media by title
  fields:
    name:
      description: Title to search for
      example: "Avatar"
    new_status:
      description: New Status
      example: "approve"
      selector:
        select:
          options:
            - "pending"
            - "approve"
            - "decline"
            - "available"
    type:
      description: Media type
      example: "movie"
      selector:
        select:
          options:
            - "movie"
            - "tv"
